// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY-dPm5vtoe-FqqmGBiophDNSY3wMUHAk',
    appId: '1:34187921016:web:683e09db7efee4eab90f8d',
    messagingSenderId: '34187921016',
    projectId: 'notesapp173',
    authDomain: 'notesapp173.firebaseapp.com',
    storageBucket: 'notesapp173.appspot.com',
    measurementId: 'G-GM2RLJZEPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqn_3nsYV5NAmT4ui48eN8MXfqduoisSU',
    appId: '1:34187921016:android:62c9cd35ecb4e180b90f8d',
    messagingSenderId: '34187921016',
    projectId: 'notesapp173',
    storageBucket: 'notesapp173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHmoNX37qH1n4XnNqpLpMoEhM2m3zQ0Q',
    appId: '1:34187921016:ios:4a6d2b6e9f752edbb90f8d',
    messagingSenderId: '34187921016',
    projectId: 'notesapp173',
    storageBucket: 'notesapp173.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHmoNX37qH1n4XnNqpLpMoEhM2m3zQ0Q',
    appId: '1:34187921016:ios:4016a13f5e57bf5fb90f8d',
    messagingSenderId: '34187921016',
    projectId: 'notesapp173',
    storageBucket: 'notesapp173.appspot.com',
    iosBundleId: 'com.example.firebaseNotes.RunnerTests',
  );
}
